export PRISMA_MIGRATION_ENGINE_BINARY="$PWD/vendor-bins/migration-engine" 
export PRISMA_QUERY_ENGINE_BINARY="$PWD/vendor-bins/query-engine" 
export PRISMA_INTROSPECTION_ENGINE_BINARY="$PWD/vendor-bins/introspection-engine" 
export PRISMA_FMT_BINARY="$PWD/vendor-bins/prisma-fmt"
echo "============================= Env ============================="
echo "PRISMA_MIGRATION_ENGINE_BINARY: $PRISMA_MIGRATION_ENGINE_BINARY"
echo "PRISMA_QUERY_ENGINE_BINARY: $PRISMA_QUERY_ENGINE_BINARY"
echo "PRISMA_INTROSPECTION_ENGINE_BINARY: $PRISMA_INTROSPECTION_ENGINE_BINARY"
echo "PRISMA_FMT_BINARY: $PRISMA_FMT_BINARY"
echo "==============================================================="
